services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    networks:
      - backend

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - backend

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"  # RedisInsight UI port
    networks:
      - backend
    depends_on:
      - redis

  maildev:
    image: maildev/maildev:latest
    ports:
      - "1080:1080"   # Web UI
      - "1025:1025"   # SMTP
    restart: unless-stopped
    environment:
      - MAILDEV_INCOMING_USER=
      - MAILDEV_INCOMING_PASS=
    networks:
      - backend

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
    driver: bridge