server:
  port: 8081
spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379
security:
  encryption:
    key: U1OxXggANfh5zyN1Guj+vFbpMAD1MfO+aGjwAuRE7m0
  jwt:
    secret: w+sxl98VWTC9QKJbi8VM42F4zRx9QgrnJz/tS12AETs=