server:
  port: 8082
spring:
  application:
    name: challenge-service
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
  thymeleaf:
    check-template-location: false
    cache: false
    enabled: true