package com.auth_example.common_service.core.responses;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    ENTITY_NOT_FOUND,
    MFA_NOT_ENABLED,
    MFA_CODE_INCORRECT,
    EMAIL_VALIDATION_REQUIRED,
    METHOD_NOT_ALLOWED,
    ENTITY_ALREADY_EXIST,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_CREDENTIAL,
    TOKEN_ERROR,
    ASSET_GENERATION_ERROR
}
