server:
  port: 8083
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=X-User-Email
        - RemoveRequestHeader=X-User-Role
        - RemoveRequestHeader=X-Internal-Use
        - AddResponseHeader=X-Gateway-Processed, true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AddRequestHeader=X-Internal-Use, gateway
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AddRequestHeader=X-Internal-Use, gateway
        - id: mfa-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/mfa/**
          filters:
            - AddRequestHeader=X-Internal-Use, gateway
        - id: auth-jwks
          uri: http://localhost:8081
          predicates:
            - Path=/.well-known/jwks.json
          filters:
            - AddRequestHeader=X-Internal-Use, gateway